title:             lam Blog
email:             1678445053@qq.com
description:       A Blog Theme by Start Bootstrap
author:            开始 Bootstrap
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://yanxiolin.github.io/Blog"

# Social Profiles
twitter_username:  SBootstrap
github_username:   yanxiolin
facebook_username: yanxiolin

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
