title:             Lam Blog
email:             1678445053@qq.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "https://yanxiolin.github.io/Blog/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   yanxiolin
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
